name: Deploy from DockerHub
on: push
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run compile

      - name: Install pm2
        run: npm install pm2@latest -g

      - name: Start pm2
        run: pm2 start

      - name: Status of pm2
        run: pm2 status

      - name: Stop pm2 app
        run: pm2 stop index

      - name: Delete pm2 app
        run: pm2 delete index

  pushing_to_docker_hub:
    runs-on: ubuntu-latest
    needs: building
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # образы докер можно публиковать в реестре (например в DockerHub или GitHub Packages)
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: . # определяет контекст сборки как набор файлов по этому пути
          push: true # при успешной сборке отправляет в реестр
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/images-convertor-ci-cd:latest

  deploying:
    runs-on: ubuntu-latest
    needs: [pushing_to_docker_hub]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Run backup script on server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_SECRET }}
          script: | 
            docker stop convertor
            docker rm convertor
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/images-convertor-ci-cd
            docker run -p 3000:3000 --name ${{ secrets.DOCKERHUB_CONTAINER_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/images-convertor-ci-cd

